import { useEffect, useRef, useState } from 'react'
import { motion } from 'framer-motion'
import { BrowserRouter, NavLink, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import { ArrowUpRight, BarChart3, Bell, BriefcaseBusiness, Check, ChevronDown, CircleHelp, FileText, LayoutDashboard, LockKeyhole, Menu, Plus, Search, Settings2, Sparkles, UploadCloud, Users, X } from 'lucide-react'
import './App.css'

const matchingSkills = ['Product strategy', 'User research', 'Figma', 'Design systems', 'Prototyping']
const missingSkills = ['SQL', 'Experimentation']

function WorkspacePage({ activeNav, analyses, metrics, authUser, onDelete, onLoadAnalysis, onLogout, onOpenAuth }) {
  if (activeNav === 'My analyses') return <section className="workspace-page"><div className="page-heading compact-heading"><div><span className="section-label">Workspace</span><h2>My analyses</h2><p>Every comparison, kept in one place.</p></div><button className="outline-button" onClick={onOpenAuth}><Plus size={17} /> New analysis</button></div><div className="history-toolbar"><div className="search-field"><Search size={15} /><input placeholder="Search roles or companies" onChange={() => {}} /></div><span>{analyses.length} saved analysis{analyses.length === 1 ? '' : 'es'}</span></div><div className="history-grid">{analyses.length ? analyses.map((item) => <article className="history-card" key={item._id}><div className="history-card-top"><span className="company-mark lilac">{(item.company || item.roleTitle || 'A')[0]}</span><span className="history-date">{new Date(item.createdAt).toLocaleDateString()}</span></div><h3>{item.roleTitle}</h3><p>{item.company || 'Untitled company'} · {item.resumeName}</p><div className="history-score"><strong>{item.score}%</strong><span>{item.matchedSkills?.length || 0} matched · {item.missingSkills?.length || 0} missing</span></div><div className="history-actions"><button className="text-button" onClick={() => onLoadAnalysis(item._id)}>View report <ArrowUpRight size={14} /></button><button className="delete-button" onClick={() => onDelete(item._id)}>Delete</button></div></article>) : <div className="empty-state"><FileText size={22} /><h3>{authUser ? 'No analyses yet' : 'Sign in to save analyses'}</h3><p>{authUser ? 'Upload a resume and compare it with a role to create your first report.' : 'The demo is available from Overview. Create an account to persist private reports.'}</p><button className="primary-button" onClick={onOpenAuth}>{authUser ? 'Start an analysis' : 'Sign in'}</button></div>}</div></section>
  if (activeNav === 'Insights') return <section className="workspace-page"><div className="page-heading compact-heading"><div><span className="section-label">Workspace</span><h2>Insights</h2><p>A clearer view of your application alignment.</p></div></div><div className="insight-grid"><div className="insight-hero"><span className="section-label">Average compatibility</span><strong>{metrics.averageScore || 0}<small>%</small></strong><p>Calculated from your saved analyses using weighted requirement coverage.</p></div><div className="metric-card"><span className="section-label">Reports saved</span><strong>{metrics.total || 0}</strong><span>Private analyses</span></div><div className="metric-card"><span className="section-label">Strong matches</span><strong>{analyses.filter((item) => item.score >= 80).length}</strong><span>80% or higher</span></div></div><div className="panel insight-table"><div className="panel-heading"><div><span className="section-label">Coverage</span><h3>Recent requirement signals</h3></div></div>{analyses.length ? analyses.slice(0, 6).map((item) => <div className="insight-row" key={item._id}><span>{item.roleTitle}</span><div className="score-bar"><span style={{ width: `${item.score}%` }} /></div><strong>{item.score}%</strong></div>) : <div className="empty-inline">Run a saved analysis to see trends here.</div>}</div></section>
  if (activeNav === 'Job tracker') return <section className="workspace-page"><div className="page-heading compact-heading"><div><span className="section-label">Workspace</span><h2>Job tracker</h2><p>Keep the roles you are actively evaluating close at hand.</p></div></div><div className="tracker-columns"><div><span className="tracker-label">In progress</span>{analyses.filter((item) => item.status === 'queued').map((item) => <div className="tracker-card" key={item._id}><BriefcaseBusiness size={17} /><div><strong>{item.roleTitle}</strong><span>{item.company || 'Company not added'}</span></div></div>)}{!analyses.some((item) => item.status === 'queued') && <div className="empty-inline">No queued roles.</div>}</div><div><span className="tracker-label">Completed</span>{analyses.filter((item) => item.status === 'complete').slice(0, 6).map((item) => <div className="tracker-card" key={item._id}><div className="tracker-score">{item.score}</div><div><strong>{item.roleTitle}</strong><span>{item.company || 'Company not added'}</span></div></div>)}{!analyses.some((item) => item.status === 'complete') && <div className="empty-inline">Your completed reports will appear here.</div>}</div></div></section>
  if (activeNav === 'Settings') return <section className="workspace-page"><div className="page-heading compact-heading"><div><span className="section-label">Account</span><h2>Settings</h2><p>Manage your CareerLens workspace.</p></div></div><div className="settings-panel panel"><div className="settings-avatar avatar avatar-coral">{authUser?.name?.slice(0, 2).toUpperCase() || 'GU'}</div><div><span className="section-label">Signed in as</span><h3>{authUser?.name || 'Guest workspace'}</h3><p>{authUser?.email || 'No account connected'}</p></div><button className="outline-button" onClick={authUser ? onLogout : onOpenAuth}>{authUser ? 'Sign out' : 'Sign in'}</button></div></section>
  return <section className="workspace-page"><div className="page-heading compact-heading"><div><span className="section-label">Support</span><h2>Help center</h2><p>Understand how CareerLens evaluates alignment.</p></div></div><div className="help-grid"><article className="panel"><CircleHelp size={20} /><h3>How scoring works</h3><p>Required skills carry the most weight. Preferred skills, experience, keywords, and education are scored separately and combined into one transparent compatibility signal.</p></article><article className="panel"><LockKeyhole size={20} /><h3>Evidence first</h3><p>CareerLens reports a skill as missing when the resume does not provide clear evidence. It never turns a guess into a qualification.</p></article></div></section>
}

function AppShell() {
  const location = useLocation()
  const navigate = useNavigate()
  const [authUser, setAuthUser] = useState(null)
  const [showAuth, setShowAuth] = useState(false)
  const [authMode, setAuthMode] = useState('login')
  const [authForm, setAuthForm] = useState({ name: '', email: '', password: '' })
  const [analyses, setAnalyses] = useState([])
  const [metrics, setMetrics] = useState({ total: 0, averageScore: 0 })
  const [fileName, setFileName] = useState('Maya_Thompson_Resume.pdf')
  const [selectedFile, setSelectedFile] = useState(null)
  const [jobText, setJobText] = useState('We are looking for a Senior Product Designer to shape the next generation of collaborative tools. You will lead discovery, translate complex problems into simple experiences, and partner closely with engineering and product.')
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [analysis, setAnalysis] = useState(null)
  const [errorMessage, setErrorMessage] = useState('')
  const fileInput = useRef(null)
  const navPaths = { Overview: '/', 'My analyses': '/analyses', Insights: '/insights', 'Job tracker': '/jobs', Settings: '/settings', 'Help center': '/help' }
  const loadWorkspace = async () => {
    const [historyResponse, metricsResponse] = await Promise.all([fetch('/api/analyses', { credentials: 'include' }), fetch('/api/analyses/metrics', { credentials: 'include' })])
    if (historyResponse.ok && metricsResponse.ok) { const history = await historyResponse.json(); const metricData = await metricsResponse.json(); setAnalyses(history.analyses || []); setMetrics(metricData) }
  }
  useEffect(() => {
    fetch('/api/auth/me', { credentials: 'include' }).then(async (response) => { if (response.ok) { const payload = await response.json(); setAuthUser(payload.user) } }).catch(() => {})
    Promise.all([fetch('/api/analyses', { credentials: 'include' }), fetch('/api/analyses/metrics', { credentials: 'include' })]).then(async ([historyResponse, metricsResponse]) => { if (historyResponse.ok && metricsResponse.ok) { const history = await historyResponse.json(); const metricData = await metricsResponse.json(); setAnalyses(history.analyses || []); setMetrics(metricData) } }).catch(() => {})
  }, [])
  const activeNav = Object.entries(navPaths).find(([, path]) => path === location.pathname)?.[0] || 'Overview'
  const handleAuth = async (event) => { event.preventDefault(); setErrorMessage(''); const endpoint = authMode === 'login' ? '/api/auth/login' : '/api/auth/register'; const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'include', body: JSON.stringify(authForm) }); const payload = await response.json(); if (!response.ok) { setErrorMessage(payload.message || 'Authentication failed'); return } setAuthUser(payload.user); setShowAuth(false); await loadWorkspace() }
  const handleLogout = async () => { await fetch('/api/auth/logout', { method: 'POST', credentials: 'include' }); setAuthUser(null); setAnalyses([]); setMetrics({ total: 0, averageScore: 0 }); navigate('/') }
  const handleDelete = async (id) => { const response = await fetch(`/api/analyses/${id}`, { method: 'DELETE', credentials: 'include' }); if (response.ok) await loadWorkspace() }
  const handleLoadAnalysis = async (id) => { const response = await fetch(`/api/analyses/${id}`, { credentials: 'include' }); if (response.ok) { const payload = await response.json(); setAnalysis({ roleTitle: payload.analysis.roleTitle, score: { overall: payload.analysis.score, components: payload.analysis.scoreComponents }, comparison: { matchedSkills: payload.analysis.matchedSkills, missingSkills: payload.analysis.missingSkills, partialMatches: payload.analysis.partialMatches }, explanation: { summary: payload.analysis.explanation } }); navigate('/') } }
  const handleFile = (event) => { const file = event.target.files?.[0]; if (file) { setSelectedFile(file); setFileName(file.name); setErrorMessage('') } }
  const loadDemo = async () => {
    setIsAnalyzing(true); setErrorMessage('')
    try { const response = await fetch('/api/analyze/demo'); const payload = await response.json(); if (!response.ok) throw new Error(payload.message); setAnalysis(payload.analysis) } catch (error) { setErrorMessage(error.message || 'Demo analysis is unavailable. Start the API with npm run server:dev.') } finally { setIsAnalyzing(false) }
  }
  const handleAnalyze = async () => {
    if (!selectedFile) { setErrorMessage('Choose a PDF or DOCX resume before analyzing.'); return }
    setIsAnalyzing(true); setErrorMessage('')
    try {
      const body = new FormData(); body.append('resume', selectedFile); body.append('roleTitle', 'Target role'); body.append('jobDescription', jobText)
      const response = await fetch('/api/analyze', { method: 'POST', body, credentials: 'include' }); const payload = await response.json()
      if (!response.ok) { if (response.status === 401) setShowAuth(true); throw new Error(payload.message || 'Analysis failed') }
      setAnalysis(payload.result); await loadWorkspace()
    } catch (error) { setErrorMessage(error.message || 'Analysis failed. Sign in before running a private analysis.') } finally { setIsAnalyzing(false) }
  }
  const scoreValue = analysis?.score?.overall ?? 82
  const displayRole = analysis?.roleTitle || 'Senior Product Designer'
  const displayMatches = analysis?.comparison?.matchedSkills?.map((item) => item.skill) || matchingSkills
  const displayMissing = analysis?.comparison?.missingSkills?.map((item) => item.skill) || missingSkills
  const evidenceRows = analysis ? [...analysis.comparison.matchedSkills, ...analysis.comparison.partialMatches, ...analysis.comparison.missingSkills].slice(0, 5) : []
  const chartData = analyses.length ? analyses.slice(0, 7).reverse().map((item) => ({ name: new Date(item.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }), score: item.score })) : [{ name: 'No data', score: 0 }]

  return (
    <div className="app-shell">
      <aside className={`sidebar ${isMenuOpen ? 'sidebar-open' : ''}`}>
        <div className="brand-row"><div className="brand-mark"><Sparkles size={16} /></div><span className="brand-name">CareerLens AI</span><button className="icon-button mobile-close" onClick={() => setIsMenuOpen(false)} aria-label="Close menu"><X size={18} /></button></div>
        <div className="workspace-switcher"><div className="avatar avatar-coral">{authUser?.name?.slice(0, 2).toUpperCase() || 'GU'}</div><div><strong>{authUser?.name || 'Guest workspace'}</strong><span>{authUser ? 'Personal workspace' : 'Demo workspace'}</span></div><ChevronDown size={15} /></div>
        <nav className="nav-list"><span className="nav-label">Workspace</span>
          {[[LayoutDashboard, 'Overview'], [FileText, 'My analyses'], [BarChart3, 'Insights'], [Users, 'Job tracker']].map(([Icon, label]) => <NavLink key={label} to={navPaths[label]} className={`nav-item ${activeNav === label ? 'active' : ''}`} onClick={() => setIsMenuOpen(false)}><Icon size={17} /><span>{label}</span>{label === 'My analyses' && <span className="nav-count">{metrics.total || 0}</span>}</NavLink>)}
          <span className="nav-label nav-label-spaced">Account</span>
          {[[Settings2, 'Settings'], [CircleHelp, 'Help center']].map(([Icon, label]) => <NavLink key={label} to={navPaths[label]} className={`nav-item ${activeNav === label ? 'active' : ''}`} onClick={() => setIsMenuOpen(false)}><Icon size={17} /><span>{label}</span></NavLink>)}
        </nav>
        <div className="sidebar-footer"><div className="upgrade-card"><div className="upgrade-icon"><Sparkles size={15} /></div><strong>Unlock your edge</strong><p>Get deeper insights and unlimited analyses.</p><button>Explore Pro <ArrowUpRight size={14} /></button></div><div className="security-note"><LockKeyhole size={14} /><span>Your data is private & encrypted</span></div></div>
      </aside>

      <main className="main-content">
        <header className="topbar"><button className="icon-button mobile-menu" onClick={() => setIsMenuOpen(true)} aria-label="Open menu"><Menu size={19} /></button><div className="breadcrumb"><span>Workspace</span><span>/</span><strong>{activeNav}</strong></div><div className="topbar-actions"><button className="icon-button" aria-label="Search"><Search size={18} /></button><button className="icon-button notification" aria-label="Notifications"><Bell size={18} /><i /></button><button className="avatar avatar-coral top-avatar" onClick={() => navigate('/settings')} aria-label="Open settings">{authUser?.name?.slice(0, 2).toUpperCase() || 'GU'}</button></div></header>
        <motion.div className="page-wrap" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .45 }}>
          {activeNav === 'Overview' ? <>
          <section className="page-heading"><div><div className="eyebrow"><span className="eyebrow-dot" /> CareerLens AI · Today</div><h1>Understand where you <span>stand out.</span></h1><p>Evidence-led resume alignment, built for your next application.</p></div><div className="heading-actions"><button className="text-button" onClick={loadDemo}><Sparkles size={15} /> Try demo</button><button className="outline-button" onClick={() => fileInput.current?.click()}><Plus size={17} /> New analysis</button></div></section>
          <section className="hero-grid">
            <motion.div className="analysis-card" initial={{ opacity: 0, x: -16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .1 }}><div className="card-kicker"><span className="kicker-icon"><Sparkles size={15} /></span><span>{isAnalyzing ? 'Reading your documents...' : 'New match analysis'}</span><span className="kicker-line" /></div><h2>Find where you<br /><em>stand out.</em></h2><p className="analysis-intro">Compare your experience against any role and see exactly what makes you a strong fit.</p><div className="analysis-steps"><div className="upload-zone" onClick={() => fileInput.current?.click()}><input ref={fileInput} type="file" accept=".pdf,.docx" onChange={handleFile} /><div className="upload-icon"><UploadCloud size={21} /></div><div><strong>{fileName}</strong><span>{selectedFile ? `${(selectedFile.size / 1024 / 1024).toFixed(1)} MB · Ready to scan` : 'Demo profile · Ready to scan'}</span></div><Check className="success-check" size={17} /></div><div className="job-input-wrap"><div className="input-label"><BriefcaseBusiness size={14} /> Job description</div><textarea value={jobText} onChange={(event) => setJobText(event.target.value)} rows="3" /><span className="char-count">{jobText.length} / 5,000</span></div></div><button className="primary-button analyze-button" onClick={handleAnalyze} disabled={isAnalyzing}><Sparkles size={16} /> {isAnalyzing ? 'Analyzing...' : 'Analyze my match'} <ArrowUpRight size={16} /></button><div className="privacy-line"><LockKeyhole size={13} /> Your resume is never shared with employers</div>{errorMessage && <div className="form-error" role="alert">{errorMessage}</div>}</motion.div>
            <motion.div className="score-card" initial={{ opacity: 0, x: 16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .2 }}><div className="card-header"><div><span className="section-label">Latest match score</span><h3>{displayRole}</h3></div><button className="more-button" aria-label="More report options">•••</button></div><div className="score-orbit"><div className="score-ring"><div className="score-number">{scoreValue}<span>%</span></div><span>{scoreValue >= 80 ? 'Strong match' : scoreValue >= 60 ? 'Promising match' : 'Needs work'}</span></div><div className="orbit-dot dot-one" /><div className="orbit-dot dot-two" /></div><div className="score-meta"><div><strong>{analysis?.score?.components?.requiredSkills ?? 82}%</strong><span>required coverage</span></div><div><strong>{displayMatches.length} / {displayMatches.length + displayMissing.length}</strong><span>key skills found</span></div></div><button className="text-button">View evidence <ArrowUpRight size={15} /></button></motion.div>
          </section>
          <section className="metrics-row"><div className="metric-card"><div className="metric-top"><span className="metric-icon mint-icon"><FileText size={16} /></span><span className="trend positive">Live <ArrowUpRight size={12} /></span></div><strong>{metrics.total}</strong><span>Saved analyses</span></div><div className="metric-card"><div className="metric-top"><span className="metric-icon peach-icon"><BriefcaseBusiness size={16} /></span><span className="trend positive">Live <ArrowUpRight size={12} /></span></div><strong>{analyses.filter((item) => item.status === 'queued').length}</strong><span>Roles in progress</span></div><div className="metric-card chart-metric"><div className="metric-top"><span className="metric-icon lilac-icon"><BarChart3 size={16} /></span><span className="trend positive">Live <ArrowUpRight size={12} /></span></div><strong>{metrics.averageScore}%</strong><span>Average match score</span><div className="mini-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="miniFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#b9a6eb" stopOpacity=".36" /><stop offset="100%" stopColor="#b9a6eb" stopOpacity="0" /></linearGradient></defs><Area type="monotone" dataKey="score" stroke="#9f8adf" strokeWidth={2} fill="url(#miniFill)" /></AreaChart></ResponsiveContainer></div></div></section>
          <section className="lower-grid"><div className="panel trend-panel"><div className="panel-heading"><div><span className="section-label">Your momentum</span><h3>Match score over time</h3></div><span className="methodology-note">Saved reports</span></div><div className="big-trend"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{ top: 10, right: 10, left: -25, bottom: 0 }}><defs><linearGradient id="trendFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#cfbdf7" stopOpacity=".4" /><stop offset="100%" stopColor="#cfbdf7" stopOpacity="0" /></linearGradient></defs><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#98939a', fontSize: 11 }} /><Tooltip contentStyle={{ background: '#252229', border: 0, borderRadius: 8, color: '#fff' }} /><Area type="monotone" dataKey="score" stroke="#ad96e8" strokeWidth={2.5} fill="url(#trendFill)" /></AreaChart></ResponsiveContainer></div></div><div className="panel skills-panel"><div className="panel-heading"><div><span className="section-label">Latest report</span><h3>Skill breakdown</h3></div><button className="more-button" aria-label="More skill options">•••</button></div><div className="skill-group"><span className="skill-title matched"><Check size={13} /> Matching</span><div className="skill-chips">{displayMatches.map((skill) => <span key={skill} className="skill-chip">{skill}</span>)}</div></div><div className="skill-group"><span className="skill-title missing"><X size={13} /> Not clearly present</span><div className="skill-chips">{displayMissing.map((skill) => <span key={skill} className="skill-chip missing-chip">{skill}</span>)}</div></div><button className="text-button report-button">Open detailed report <ArrowUpRight size={15} /></button></div></section>
          {analysis && <section className="evidence-panel panel"><div className="panel-heading"><div><span className="section-label">Explainable analysis</span><h3>{analysis.explanation?.summary}</h3></div><span className="methodology-note">Deterministic weighted score</span></div><div className="evidence-list">{evidenceRows.map((item) => <div className="evidence-row" key={`${item.status}-${item.skill}`}><span className={`evidence-status ${item.status}`}>{item.status === 'matched' ? '✓' : item.status === 'partial' ? '~' : '×'}</span><div><strong>{item.skill}</strong><p>{item.evidence}</p></div><span className="evidence-label">{item.status}</span></div>)}</div></section>}
          <section className="recent-section"><div className="section-heading"><div><span className="section-label">Keep going</span><h3>Recent analyses</h3></div><NavLink className="text-button" to="/analyses">View all <ArrowUpRight size={15} /></NavLink></div><div className="recent-list">{analyses.length ? analyses.slice(0, 3).map((item) => <div className="recent-item" key={item._id}><div className="company-mark lilac">{(item.company || item.roleTitle || 'A')[0]}</div><div className="recent-role"><strong>{item.roleTitle}</strong><span>{item.company || 'Untitled company'} · {new Date(item.createdAt).toLocaleDateString()}</span></div><div className="recent-score"><div className="score-bar"><span style={{ width: `${item.score}%` }} /></div><strong>{item.score}%</strong></div><button className="arrow-button" onClick={() => handleLoadAnalysis(item._id)} aria-label={`Open ${item.roleTitle}`}><ArrowUpRight size={16} /></button></div>) : <div className="empty-inline">Sign in and save an analysis to build your history.</div>}</div></section>
          </> : <WorkspacePage activeNav={activeNav} analyses={analyses} metrics={metrics} authUser={authUser} onDelete={handleDelete} onLoadAnalysis={handleLoadAnalysis} onLogout={handleLogout} onOpenAuth={() => setShowAuth(true)} />}
        </motion.div>
      </main>
      {showAuth && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setShowAuth(false) }}><form className="auth-modal" onSubmit={handleAuth}><button className="modal-close icon-button" type="button" onClick={() => setShowAuth(false)} aria-label="Close authentication dialog"><X size={18} /></button><span className="section-label">CareerLens AI</span><h2>{authMode === 'login' ? 'Welcome back' : 'Create your workspace'}</h2><p>{authMode === 'login' ? 'Sign in to access saved analyses and private reports.' : 'Save your resume comparisons and return to them anytime.'}</p>{authMode === 'register' && <label>Name<input required value={authForm.name} onChange={(event) => setAuthForm({ ...authForm, name: event.target.value })} /></label>}<label>Email<input required type="email" value={authForm.email} onChange={(event) => setAuthForm({ ...authForm, email: event.target.value })} /></label><label>Password<input required minLength="8" type="password" value={authForm.password} onChange={(event) => setAuthForm({ ...authForm, password: event.target.value })} /></label>{errorMessage && <div className="modal-error" role="alert">{errorMessage}</div>}<button className="primary-button auth-submit" type="submit">{authMode === 'login' ? 'Sign in' : 'Create account'}</button><button className="text-button auth-switch" type="button" onClick={() => { setAuthMode(authMode === 'login' ? 'register' : 'login'); setErrorMessage('') }}>{authMode === 'login' ? 'Create a new account' : 'I already have an account'}</button></form></div>}
    </div>
  )
}

function App() {
  return <BrowserRouter><Routes><Route path="/" element={<AppShell />} /><Route path="/analyses" element={<AppShell />} /><Route path="/insights" element={<AppShell />} /><Route path="/jobs" element={<AppShell />} /><Route path="/settings" element={<AppShell />} /><Route path="/help" element={<AppShell />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></BrowserRouter>
}

export default App
